<?php
/**
 +-----------------------------------------------------------------------+
 | plugins/sendcharset/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Send charset/encoding hack plugin  |
 |                                                                       |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['sendcharset'] = 'Charset for message to send';
?>
