<?php
/**
 +-----------------------------------------------------------------------+
 | plugins/sendcharset/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Send charset/encoding hack plugin  |
 |                                                                       |
 +-----------------------------------------------------------------------+
*/

$labels['sendcharset'] = '送信に使用する文字セット';
$labels['usebase64'] = 'MIMEのエンコーディングにBase64を使用する';
?>
